apiVersion: v1
kind: Service
metadata:
  name: {{ include "zmq-client-server-example-chart.fullname" . }}
  labels:
    {{- include "zmq-client-server-example-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5557
      protocol: TCP
#      name: http
  selector:
    {{- include "zmq-client-server-example-chart.selectorLabels" . | nindent 4 }}
